---
site_name: My Notes

theme:
  name: terminal
  palette: gruvbox_dark
  features:
    - footer.prev_next
    # - navigation.side.hide
    - navigation.side.indexes
    - navigation.side.toc.hide
    # - navigation.top.hide
    # - navigation.top.cursor_animation.hide
    # - navigation.top.search_button.hide
    - revision.date
    - revision.history
    # - style.links.underline.hide

plugins:
  - search
  - git-revision-date

repo_url: https://github.com/thamenato/my-notes
edit_uri: edit/main/docs/
